/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASpace: typeof import('ant-design-vue/es')['Space']
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
    FunctionCard: typeof import('./src/components/functionCard.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    InterviewCard: typeof import('./src/components/interviewCard.vue')['default']
    InterviewCreate: typeof import('./src/components/interviewCreate.vue')['default']
    InterviewDetail: typeof import('./src/components/interviewDetail.vue')['default']
    InterviewShow: typeof import('./src/components/interviewShow.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    MarqueeText: typeof import('./src/components/MarqueeText.vue')['default']
    NewInterview: typeof import('./src/components/newInterview.vue')['default']
    PersonCard: typeof import('./src/components/personCard.vue')['default']
    PersonDetail: typeof import('./src/components/personDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./src/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./src/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./src/components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./src/components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./src/components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./src/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    Switch: typeof import('./src/components/ui/switch/Switch.vue')['default']
    TagSelect: typeof import('./src/components/tagSelect.vue')['default']
    TagsInput: typeof import('./src/components/ui/tags-input/TagsInput.vue')['default']
    TagsInputInput: typeof import('./src/components/ui/tags-input/TagsInputInput.vue')['default']
    TagsInputItem: typeof import('./src/components/ui/tags-input/TagsInputItem.vue')['default']
    TagsInputItemDelete: typeof import('./src/components/ui/tags-input/TagsInputItemDelete.vue')['default']
    TagsInputItemText: typeof import('./src/components/ui/tags-input/TagsInputItemText.vue')['default']
    Textarea: typeof import('./src/components/ui/textarea/Textarea.vue')['default']
    ToggleTheme: typeof import('./src/components/ui/switch/toggleTheme.vue')['default']
  }
}
